### ISSUE TITLE
Bad handler for non-standard version description - it is OK for v1.2.3, but what about v1.2.3-1 ?

### ISSUE THREAD

**Issue by JWicher** [tmakuch/dependency-version-checker#2]
It fails when some one release version in non-standard description. It recognize v1.2.3. but not v1.2.3-2. (The case is that "**-2**"").

**Comment by tmakuch** [comment]
Resolved with 1af5cd1718700f6598f9ddfc7de8b41fccb29b4f. Released in v1.1.0
